
	function getAgreement(username,name,course,path,signDate,price){
		price = (price==0 ? price="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;":price)
		var arr = new Array();
		arr.push('<div style="page-break-after:always">&nbsp;</div>');
		arr.push('<div style="">');
		arr.push('	<div style="text-align:center; margin:25px 0 20px 0;"><h2 style="font-size:1.7em;">培训协议书（2022版）</h2></div>');
		arr.push('</div>');
		arr.push('<div style="float:left;width:100%;">');
		arr.push('	<table style="width:100%; padding-left:10px;margin-top:25px;">');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">明确甲乙双方的义务，经平等、自愿、协商签订本“培训协议书”。具体约定如下：</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:30px;line-height:50px;">1、乙方[' + name + ']身份证号[' + username + ']，自主选择[' + course + ']培训项目，培训费为' + price + '元（包括培训费和申报鉴定代办费），乙方缴纳' + price + '元（由单位支付培训费无需缴纳）。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">2、乙方已详细阅读学校报名处公告栏上各项公示内容（属于单位集体报名的学员，开班当天必须自己到报名处去阅读各项公示内容），如有不解之处直接向报名处工作人员咨询详解，并自动向班主任加入培训微信群，建立信息联系方式。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">3、该培训项目实行考培分离制度，学校负责培训，考试由甲方向相关鉴定机构申报考试（或由乙方向相关鉴定机构申报考试，也可请甲方协助申报），如甲方自己培训考证项目，此条款不用。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">4、乙方在开班前申请退学，甲方将收取20元培训报名手续费。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">5、乙方在开班后（包括线上、线下）申请退学，具体处理如下：</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:70px;">1）开班1～2天，甲方收取培训总费用的30%（包含书杂费）。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:70px;">2）培训项目课时≤100课时，开班超过2天，培训总费用不予退还。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:70px;">3）开班3～4天，甲方收取培训总费用的50%（包含书杂费）。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:70px;">4）开班超过4天，培训总费用不予退还。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:70px;">5) 申请退费的学员，须携带缴费票据原件办理退费,未提供缴费票据原件不予退费。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">6、乙方上课期间必须自觉履行签到考勤制度，如上课本人没有签到，作为缺课处理。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">7、乙方考试不及格，需自己至甲方报名处申请补考（或电话询问考试机构相关补考事宜）。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">8、乙方在报名表上填写的各项报名信息必须正确（特别是手机号要正确），需本人亲自签名，如因以上信息错误而造成差错的责任由乙方承担。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">9、乙方必须关注对应项目培训微信群内的信息，如因未关注培训微信群信息而造成差错的责任由乙方承担。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">10、本协议一式二份，甲、乙双方各执一份，乙方在签字前应认真阅读本协议各项条款内容，本协议一经签字立即生效。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:30px;"><p style="font-size:1.3em;text-indent:50px;"></p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td  style="height:50px;"><p style="font-size:1.3em;text-indent:50px;">甲方：上海智能消防学校</p></td>');
		arr.push('			<td  style="height:50px;"><p style="font-size:1.3em;">乙方（签字）：</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td style="height:50px;"><p style="font-size:1.3em;text-indent:50px;">（单位盖章）</p></td>');
		arr.push('			<td></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td style="height:30px;"><p style="font-size:1.3em;text-indent:50px;">日&nbsp;&nbsp;&nbsp;&nbsp;期：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;年&nbsp;&nbsp;&nbsp;&nbsp;月&nbsp;&nbsp;&nbsp;&nbsp;日</p></td>');
		arr.push('			<td style="height:30px;"><p style="font-size:1.3em;">日&nbsp;&nbsp;&nbsp;&nbsp;期：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' + signDate + '</p></td>');
		arr.push('		</tr>');
		arr.push('	</table>');
		arr.push('</div>');
		
		if(path>""){
			//alert(path);
			arr.push('<div style="position: relative;width:100%;height:80%;">');
			arr.push('<div style="position: absolute; z-index:10;">');
			arr.push('<div style="float:left;">');
			arr.push('	<span><img src="/users' + path + '?times=' + (new Date().getTime()) + '" style="width:170px;margin:0px 0px 8px 480px;padding-left:80px;padding-top:735px;"></span>');
			arr.push('</div>');
			arr.push('</div>');
			arr.push('<div style="position: absolute; z-index:10;">');
			arr.push('<div style="float:left;">');
			arr.push('	<span><img src="/users/upload/companies/stamp/znxf.png" style="width:200px;margin:0px 0px 8px 50px;padding-left:80px;padding-top:720px;"></span>');
			arr.push('</div>');
			arr.push('</div>');
			arr.push('</div>');
		}
		/**/
		$("#agreementCover").html(arr.join(""));
	}
