
	function getAgreement(username,name,course,path,signDate,price,priceStandard,fmt,priceExam=0){
		price = (price==0 ? price="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;":price);
		let top1 = 0;
		let top2 = 0;
		let arr = new Array();
		if(keyID == 4){
			arr.push('<div style="page-break-after:always">&nbsp;</div>');
		}
		arr.push('<div style="">');
		arr.push('	<div style="text-align:center; margin:25px 0 0 0;"><h2 style="font-size:1.7em;">培训协议书</h2></div>');
		arr.push('</div>');
		arr.push('<div style="float:left;width:100%;">');
		arr.push('	<table style="width:100%; padding-left:10px;margin-top:25px;">');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">为了确保培训学员[' + name + ']身份证号[' + username + ']（乙方）和上海智能消防学校（甲方）的权益，明确甲乙双方的义务，经平等、自愿、协商签订本“培训协议书”。具体约定如下：</p></td>');
		arr.push('		</tr>');
		if(fmt==="A3"){
			// 人社项目
			let t = 475;
			top1 = 1280 - t;
			top2 = 1340 - t;
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;line-height:50px;">一、培训项目</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;line-height:50px;">1、乙方自主选择参加甲方举办的[' + course + ']职业(等级)职业技能培训。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2、具体培训日期及安排见课表。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;line-height:50px;">二、培训收退费</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;line-height:50px;">乙方已知悉本次报名的课程内容，并承诺按照甲方的教学计划及协议约定参加培训，遵守甲方的“学员守则及相关管理要求”。乙方需如实填写学员相关信息，提交本人真实资料。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;line-height:50px;">1、收费方式</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">经双方约定，乙方参加培训应支付培训考试费总额为 (人民币): ' + priceStandard + '元，其中：培训费' + (priceStandard - priceExam) + '元，考试费' + priceExam + '元 (以申报年度社会培训评价组织有关操作事项的通知为准，考试费包括理论知识、操作技能一次考试费用)。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;line-height:50px;">2、退费规定</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">本着为稳定学校秩序，维护办学机构和学员的合法利益，规范社会力量办学退费行为，参照上海市关于民办教育管理的有关规定，退费规定如下:</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2.1 乙方缴费时请先阅读学校公示的“收费和退费制度”，考虑周全，然后缴费。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2.2 因甲方原因造成无法如期开课的，甲方全额退回所有费用。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2.3 在开课前，乙方因故不能参加培训，乙方填写退费申请单办理退费手续（需支付20元退学手续费）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2.4 开课后，乙方因故不能继续参加培训要求退还培训费（以培训课程表课时为准）：</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2.4.1 上课时间不满8课时，扣除一天学费，退还剩余学费；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2.4.2 上课时间超过8课时，不满总课时三分之一，退还50%的学费；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2.4.3 上课时间超过三分之一，不满三分之二的，退还20%的学费；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2.4.4 上课时间超过总课时三分之二的，学费将不予退还。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">2.5 本次职业技能培训已上课的学员班级已做考试申报，考试费不予以退还。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2.6 退费需凭缴费发票、填写退费申请，提供同报名时姓名身份证一致的银行卡号及开户银行信息。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">3、缺课缺考说明</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">3.1 乙方缺席课程（请假）视做自动放弃，不补课，不退费。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">3.2 学员因故错过考试时间，需要申报下期考试的，需重新支付考试费（代办费）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">4.	赠课说明</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">4.1 学员报名本培训项目时所享受的赠送课程须自本协议生效之日起半年内完成培训使用，逾期未使用的，赠课资格自动失效，不予补发、不予折现。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">4.2 学员报名本培训项目时所享受的赠送课程，均以学员完整履行合同义务、正常完成课程学习为前提。学员申请退费、解除或终止本协议的，不再享有任何赠课资格；如赠送课程已实际使用，退费结算时须按该课程原价足额扣除相应费用。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">三、培训补贴方式</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">根据《上海市人力资源和社会保障局 上海市财政局关于进一步完善职业技能提升补贴政策的通知》沪人社规(2025) 7号，补贴对象范围内的劳动者参加补贴项目的职业技能等级认定，并取得相应职业技能等级证书，可自证书核发之日起12个月内，自行通过上海人社APP或前往各区就业促进中心申请职业技能提升补贴。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">四、甲方的权利义务</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">4.1 甲方应根据培训规律和工作实际，对招收的学员及时组班，安排培训。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">4.2 甲方应组织乙方参加职业技能等级认定考试，对考试合格的学员，及时通知领取相应证书；如乙方考试不合格并有补考意愿，甲方应组织乙方参加补考（竞赛项目无补考）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">五、乙方的权利义务</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">5.1 乙方可以根据本市相关规定，完成培训和考试后，根据考试结果后自行完成补贴申请，享受培训费补贴。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">5.2 乙方应按照甲方制定的教学计划及协议约定参加培训，遵守甲方的教学管理制度及相关管理要求。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">5.3 乙方应严格依照《国家职业标准》规定的申报条件，配合甲方完成考试申报工作，并承诺所提供的全部资料真实、合法、有效。乙方应在培训结束后，按本市相关规定参加相应职业技能等级认定考试。若乙方自培训结束之日起六个月内未参加考试，视为自动放弃甲方提供的考试协调服务，甲方不再为乙方协调考试报名及相关事宜，后续考试由乙方自行与考试机构对接。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">六、其他</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">1、甲乙双方的协议约定与国家法律法规存在不一致的，以国家法律法规为准。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2、甲乙双方应对提供材料及信息的真实性负责，提供虚假信息的，各自承担相应责任。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">3、在履行本协议过程中发生的争议，甲乙双方可协商解决，未能达成一致的，可向甲方所在地人民法院提起诉讼。</p></td>');
			arr.push('		</tr>');
		}
		if(fmt==="A2"){
			// 消防项目
			top1 = 1320;
			top2 = 1380;
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;line-height:50px;">1、乙方自主选择[' + course + ']培训项目，该项目培训费为：' + priceStandard + '元（包括培训费、申报考试鉴定费等），乙方缴纳' + price + '元（由单位支付培训费的部分无需缴纳）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2、乙方已详细阅读甲方报名处公示的各项内容（属于单位集体报名的学员，开班当天须本人到报名处阅读各项公示内容，如有不解之处可向报名处工作人员咨询）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">3、该培训项目实行考培分离制度，学校负责培训，乙方自行向相关鉴定机构申报考试，若乙方在申报时遇到困难，可向甲方提出协助。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">4、甲方按课表提供师资、课程及教学场地。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">5、甲方提供必要的学习支持（如答疑、资料等）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">6、甲方保护学员个人信息，不无故泄漏或滥用信息。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">7、甲方为乙方培训开通的学习账号，只限乙方本人使用，乙方不可将账号进行转让、共享等。如账号出现异常行为，甲方有权暂停或取消账号的登录权限。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">8、乙方在办理报名手续后，如要退学退费按以下规则处理：</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">1）乙方完成付费次日起的 3个自然日内，相关培训服务尚未实施前，乙方可以单方面解除本协议，并向甲方申请退回已交付的培训费，甲方收取30元服务费。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">2）乙方在开课前、付费超过3个自然日申请退学退费，甲方收取培训费5%服务费。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">3）开课后：</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">① 课程第一天乙方申请退学退费的，扣除10%培训费及书本费，退还剩余培训费；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">② 课程第二天乙方申请退学退费的，扣除30%培训费及书本费，退还剩余培训费；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">③ 课程第三天乙方申请退学退费的，扣除60%培训费及书本费，退还剩余培训费；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">④ 课程第四天乙方申请退学退费的，培训费不予退还。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">4)  乙方申请退学须携带缴费票据原件和身份证，填写退款申请，未提供缴费票据原件的不予退费。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">9、培训期间乙方资料遗失需要再次补发，需按规定支付相应费用，书本费按照书本实际标价支付，实操资料手册按照20元/本支付。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">10、乙方上课期间必须自觉履行签到考勤制度，如本人没有签到，不来上课，做缺课处理，因缺课所产生的一切相关后果，均由乙方自行承担全部责任。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">11、乙方承诺报名的各项信息和资料真实、有效、正确，如乙方弄虚作假、不符合报名培训考试的规定而入学，所产生的一切后果自负，且一律不退任何费用。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">12、乙方报名后须关注该培训项目班级群内由学校发布的相关培训和考试信息，如乙方因未关注班级群里甲方发布的信息或乙方手机号填写不正确而没有收到相关信息，乙方应承担由此而引起的一切责任。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">13、 其他条款：</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">1）消防设施操作员的考试安排与资料审核机制具有阶段性差异，乙方须依照消防职业技能鉴定考试网官方发布的具体要求，配合提供所需的各类资料。乙方务必要关注消防鉴定考试网，若因鉴定站官方对报名资格、资料等事项要求进行调整，由于乙方未关注而导致乙方不符合报名条件无法正常参加考试，由此产生的一切损失，均由乙方自行承担。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2）根据消防行业职业技能鉴定指导中心相关公告《消防设施操作员国家职业标准（2026年版）》，将于2026年10月1日正式施行。新政施行后消防设施操作员职业将不再区分维保、监控两个职业方向，实现两证合一，所有考生将统一按照新政《消防设施操作员职业技能鉴定考核大纲（2026年版）》开展考核鉴定工作。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">3）乙方现阶段报名培训并计划参加考试，属于新、旧《标准》交替过渡阶段，考生按照现在考核大纲只能参加一次考试，如果考试不合格未能取得职业资格证书，需重新申报按新政考纲的要求考试。届时乙方如需补充学习新政考纲要求的考核内容，可选择报名甲方针对新政考核内容设置的实操补充培训。重新培训报名前双方需要重新签署培训协议，明确补充培训内容、双方权利义务。补充培训的具体内容、收费标准，以甲方报名处公示的正式培训价格为准，乙方报名前可向甲方咨询完整公示内容，确认无误后再行报名。</p></td>');
			arr.push('		</tr>');
		}
		if(fmt==="A1"){
			// 安监项目
			let t = 475;
			// top1 = 1280 - t;
			// top2 = 1340 - t;
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">1、乙方自主选择[' + course + ']培训项目，该项目培训费为：' + priceStandard + '元（含首次考试鉴定费60元），乙方缴纳' + price + '元（由单位支付培训费的部分无需缴纳）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2、乙方已详细阅读甲方报名处公示的各项内容（属于单位集体报名的学员，开班当天须本人到报名处阅读各项公示内容，如有不解之处可向报名处工作人员咨询）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">3、该培训项目实行考培分离制度，学校负责培训。申请考试分两种情况：</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">① 乙方按要求完成培训学时后，由甲方统一申请考试。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">② 乙方符合《关于推进职业技能证书互通互认的通知》（人社厅发〔2026〕1 号）相关规定的，乙方自行前往具备相应考试项目的考试点提交考试申请材料申请考试。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">4、甲方按课程表提供师资、课程及教学场地。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">5、甲方提供必要的学习支持（如答疑、资料等）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">6、甲方保护学员个人信息，不无故泄漏或滥用信息。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">7、甲方为乙方培训开通的网上学习账号，只限乙方本人使用，乙方不可将该账号进行转让、共享等行为。如乙方学习账号出现异常行为，甲方有权暂停或取消账号的登录权限。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">8、乙方在办理报名手续后 ，如要退学退款按以下规则处理：</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">1）开课前，乙方申请退学退费，甲方收取30元的手续费。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">2）开课后（线下）：</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">①课程第一天乙方申请退学退费的，扣除10%培训费，退还剩余培训费；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">② 课程第二天乙方申请退学退费的，扣除50%培训费，退还剩余培训费；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">③ 课程第三天乙方申请退学退费的，培训费不予退还。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">3) 乙方申请退学退费须携带缴费凭证和本人身份证，填写退款申请，未提供缴费凭证的不予退费。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">9、乙方承诺报名提供的各项信息真实、有效、正确，且本人签名。如乙方弄虚作假、不符合报名培训考试的规定而入学，所产生的—切后果自负，且—律不退任何费用。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">10、乙方报名后须关注该培训项目班级群内由学校发布的相关培训考试信息，如因未关注班级群信息或手机号填写不正确而没有收到相关信息，乙方应承担由此而引起的—切责任。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">11、乙方上课期间必须自觉履行签到考勤制度，如本人没有签到，不来上课，作缺课处理。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">12、《特种作业人员安全技术培训考核管理规定》（应急管理部令第 19 号，2026 年 6 月 1 日施行）对培训学时、考试申报、考核规则作出强制性新规要求，如乙方未按要求完成线上及线下的培训学时，甲方无法为乙方提供学时证明，无法为乙方申报考试。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">13、若乙方考试不及格需要申请补考的，需自行向甲方提出申请，甲方协助乙方申报考试。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">14、本次缴纳的培训费仅限乙方享受本期的国家标准课程培训服务。乙方考试未合格，申请补课、重学课程或需要甲方提供其他延伸服务的，须由乙方另行缴纳相应费用，甲方不再免费提供相关服务。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">15、协议期限：</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">按照应急部19号令考试规则，理论考试（1次正考1次补考）合格后方可参加实操考试；实操最多10次（5次正考5次补考）考核机会。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">1）本培训协议服务期限自本协议签订当日起生效，有效期一年。乙方须在一年服务期内足额完成全部培训课时，且完成考试申报手续。若乙方未在上述期限内完成课时培训及考试申报，服务期届满时本协议自动终止，甲方已收取的培训费不予退还。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">2）乙方理论考试2次（初考+补考）均不合格，本次培训服务结束。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">3）乙方培训结束，理论考试通过后，实操考试2次（正考1次+补考1次）后，本次培训服务结束，不再享受免费的实操培训及实操开放日服务。</p></td>');
			arr.push('		</tr>');
		}
		if(fmt==="A0"){
			// 普通项目
			let t = 475;
			top1 = 1280 - t;
			top2 = 1340 - t;
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;line-height:50px;">1、乙方自主选择[' + course + ']培训项目，该项目培训费为：' + priceStandard + '元（包括培训费、申报考试鉴定费等），乙方缴纳' + price + '元（由单位支付培训费的部分无需缴纳）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">2、乙方已详细阅读甲方报名处公示的各项内容（属于单位集体报名的学员，开班当天须本人到报名处阅读各项公示内容，如有不解之处可向报名处工作人员咨询）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">3、该培训项目实行考培分离制度，学校负责培训。申请考试分两种情况：① 上海市应急管理局和社会评价机构（人社局）发证项目，由甲方统一申请考试； ② 其他考试项目由乙方自行向相关鉴定机构申报考试，若乙方申报遇到困难，可向甲方提出协助（甲方发证培训考核项目，此条款不适用）。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">4、乙方在办理报名手续后，扫甲方二维码登陆后即进入了甲方线上教学平台开始学习，如要退学退款按以下规则处理：</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">1）报名后三天内申请退学，甲方收取20元报名手续费和书本费（书本不予退还）后退款；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">2）报名后超过三天申请退学，甲方收取培训费的20%，退款金额为原支付金额的80%；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">3）报名后超过五天申请退学，甲方收取培训费的30%，退款金额为原支付金额的70%；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">4）开始线下培训的第二天申请退学，甲方收取培训费的50%，退款金额为原支付金额的50%；</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">5) 开始线下培训的第三天申请退学，培训费不予退还。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:3.5em;">6) 乙方申请退学须携带缴费票据原件和身份证，填写退款申请，未提供票据原件的不予退费。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">5、乙方上课期间必须自觉履行签到考勤制度，如本人没有签到，不来上课，作缺课处理。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">6、乙方因自身原因未参加考试，作缺考处理；如要再次参加考试，须缴纳相关费用。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">7、乙方承诺报名的各项信息真实、有效、正确，且本人签名。如乙方弄虚作假、不符合报名培训考试的规定而入学，所产生的一切后果自负，且一律不退任何费用。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">8、乙方报名后须关注该培训项目班级群内由学校发布的相关培训考试信息，如因未关注班级群信息或手机号填写不正确而没有收到相关信息，乙方应承担由此而引起的一切责任。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">9、乙方未完成线上理论教学80%的课时学习或线下80%的课时学习，甲方有权不予申报考试。</p></td>');
			arr.push('		</tr>');
			arr.push('		<tr>');
			arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">10、若乙方考试不及格，需自行到甲方报名处重新申请培训考试，并重新缴纳培训考试费。</p></td>');
			arr.push('		</tr>');
		}
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;">本协议一式二份，甲、乙双方各执一份。经乙方在线签名的电子文本具有同等法律效力。</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td colspan="2" style="height:25px;"><p style="font-size:1em;text-indent:2em;"></p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td  style="height:50px;"><p style="font-size:1em;text-indent:2em;">甲方：上海智能消防学校</p></td>');
		arr.push('			<td  style="height:50px;"><p style="font-size:1em;">乙方（签字）：</p></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td style="height:50px;"><p style="font-size:1em;text-indent:2em;">（盖章）</p></td>');
		arr.push('			<td></td>');
		arr.push('		</tr>');
		arr.push('		<tr>');
		arr.push('			<td style="height:25px;"><p style="font-size:1em;text-indent:2em;">日&nbsp;&nbsp;&nbsp;&nbsp;期：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;年&nbsp;&nbsp;&nbsp;&nbsp;月&nbsp;&nbsp;&nbsp;&nbsp;日</p></td>');
		arr.push('			<td style="height:25px;"><p style="font-size:1em;">日&nbsp;&nbsp;&nbsp;&nbsp;期：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' + signDate + '</p></td>');
		arr.push('		</tr>');
		arr.push('	</table>');
		arr.push('</div>');
		
		if(path>""){
			// let a_ml = (kyeID==2?350:250);
			let a_ml = 300;
			let a_tk = 935;
			if(keyID==2){
				if(fmt==="A1"){
					a_tk = 935;
				}
				if(fmt==="A2"){
					a_ml = 350;
					a_tk = 100;
				}
				if(fmt==="A3"){
					a_ml = 350;
					a_tk = 100;
				}
			}
			top1 = a_tk;
			top2 = a_tk;
			alert(keyID);
			arr.push('<div style="position: relative;width:100%;height:70%;">');
			arr.push('<div style="position: absolute; z-index:10; width:200px;">');
			// arr.push('	<span><img src="/users/upload/companies/stamp/znxf.png" style="opacity:0.6; width:200px;margin:0px 0px 8px 50px;padding-left:80px;padding-top:' + top2 + 'px;"></span>');
			arr.push('<img src="/users/upload/companies/stamp/znxf.png" style="opacity:0.6; width:200px;margin:0px 0px 8px 50px;padding-left:50px;padding-top:' + top1 + 'px;">');
			arr.push('</div>');
			arr.push('<div style="position: absolute; z-index:10; width:200px; margin-left:200px;">');
			// arr.push('	<span><img src="/users' + path + '?times=' + (new Date().getTime()) + '" style="width:170px;margin:0px 0px 8px 480px;padding-left:80px;padding-top:' + top1 + 'px;"></span>');
			arr.push('<img src="/users' + path + '?times=' + (new Date().getTime()) + '" style="width:170px;margin:0px 0px 8px ' + a_ml + 'px;padding-left:60px;padding-top:' + top2 + 'px;">');
			arr.push('</div>');
			arr.push('</div>');
			arr.push('<div style="clear: both;"></div>');
		}
		/**/
		$("#agreementCover").html(arr.join(""));
	}
